package de.caritas.cob.userservice.api.workflow.accountinactivity;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.*;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class AccountInactivityServiceTest {
  @Test
  void failedCreationCleanupDeletesOnlyMatchingUnprogressedSnapshot() {
    var service = createService(new Effects());
    var captured = Instant.parse("2026-01-01T00:00:00.123456Z");
    service.assignAtCreation("failed", 1L, 24, 7, captured);
    assertThat(service.discardUncompletedCreation("failed", 12, 7, captured)).isFalse();
    assertThat(service.discardUncompletedCreation("failed", 24, 8, captured)).isFalse();
    assertThat(service.discardUncompletedCreation("failed", 24, 7, captured.plusSeconds(1)))
        .isFalse();
    assertThat(service.discardUncompletedCreation("failed", 24, 7, captured)).isTrue();
    assertThat(service.snapshot("failed")).isEmpty();
    assertThat(service.discardUncompletedCreation("failed", 24, 7, captured)).isFalse();
    service.assignAtCreation("active", 1L, 24, 7, captured);
    service.recordActivity("active", captured.plusSeconds(1));
    assertThat(service.discardUncompletedCreation("active", 24, 7, captured)).isFalse();
    service.assignAtCreation("suspended", 1L, 24, 7, captured);
    service.suspend("suspended");
    assertThat(service.discardUncompletedCreation("suspended", 24, 7, captured)).isFalse();
    service.reactivate("suspended");
    assertThat(service.discardUncompletedCreation("suspended", 24, 7, captured)).isFalse();
  }

  @Test
  void creationSnapshotSurvivesChangedDefaultsAndUsesCalendarMonths() {
    var ds = new DriverManagerDataSource("jdbc:h2:mem:inactivity;DB_CLOSE_DELAY=-1", "sa", "");
    var jdbc = new JdbcTemplate(ds);
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity");
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity_journal");
    jdbc.execute(
        "CREATE TABLE account_inactivity_journal(journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY,identity_id VARCHAR(36),action VARCHAR(30),target VARCHAR(30),outcome"
            + " VARCHAR(40),created_at TIMESTAMP(6))");
    jdbc.execute(
        "CREATE TABLE account_inactivity(identity_id VARCHAR(36) PRIMARY KEY,tenant_id"
            + " BIGINT,assigned_months INT NOT NULL,revision BIGINT NOT NULL,last_activity"
            + " TIMESTAMP(6) NOT NULL,due_at TIMESTAMP(6) NOT NULL,status VARCHAR(20) NOT"
            + " NULL,last_error VARCHAR(1000),attempts INT DEFAULT 0 NOT NULL)");
    var service =
        new AccountInactivityService(
            jdbc,
            new DataSourceTransactionManager(ds),
            Clock.fixed(Instant.parse("2026-02-15T12:00:00Z"), ZoneOffset.UTC),
            new Effects());
    service.assignAtCreation("person", 1L, 1, 1, Instant.parse("2026-01-31T12:00:00Z"));
    service.assignAtCreation("person", 1L, 24, 2, Instant.parse("2026-02-01T12:00:00Z"));
    var snapshot = service.snapshot("person").orElseThrow();
    assertThat(snapshot.assignedMonths()).isEqualTo(1);
    assertThat(snapshot.dueAt()).isEqualTo(Instant.parse("2026-02-28T12:00:00Z"));
    service.recordActivity("person", Instant.parse("2026-02-15T10:00:00Z"));
    assertThat(service.snapshot("person").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("2026-03-15T10:00:00Z"));
  }

  @Test
  void dueAskerDeletesOnlyAfterConfirmedEffectAndDryRunDoesNothing() {
    var service =
        createService(
            new Effects() {
              public boolean delete(String id) {
                return false;
              }
            });
    service.assignAtCreation("due", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.scan(true);
    assertThat(service.snapshot("due").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.ACTIVE);
    service.scan(false);
    assertThat(service.snapshot("due").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.DELETING);
    var retry = createServiceWithoutReset(new Effects());
    retry.scan(false);
    assertThat(retry.snapshot("due").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.DELETED);
  }

  @Test
  void mixedRolesSuspendAndOnlyExplicitReactivationRestartsClock() {
    var service =
        createService(
            new Effects() {
              public Set<Role> currentRoles(String id) {
                return Set.of(Role.ASKER, Role.OTHER);
              }
            });
    service.assignAtCreation("mixed", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.scan(false);
    assertThat(service.snapshot("mixed").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDED);
    service.recordActivity("mixed", Instant.parse("2026-02-01T00:00:00Z"));
    assertThat(service.snapshot("mixed").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDED);
    assertThat(service.reactivate("mixed")).isTrue();
    assertThat(service.snapshot("mixed").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("2026-03-01T00:00:00Z"));
  }

  @Test
  void explicitSuspensionIsRetryableAndDoesNotDelete() {
    var service =
        createService(
            new Effects() {
              public boolean suspend(String id) {
                return false;
              }
            });
    service.assignAtCreation("manual", 1L, 24, 1, Instant.parse("2026-01-01T00:00:00Z"));
    assertThat(service.suspend("manual")).isFalse();
    assertThat(service.snapshot("manual").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDING);
    var retry = createServiceWithoutReset(new Effects());
    retry.scan(false);
    assertThat(retry.snapshot("manual").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDED);
  }

  @Test
  void largePositiveMonthsSaturateDatabaseDateRangeWithoutRejectingPolicy() {
    var service = createService(new Effects());
    service.assignAtCreation(
        "long", 1L, Integer.MAX_VALUE, 1, Instant.parse("2026-01-01T00:00:00Z"));
    assertThat(service.snapshot("long").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("9999-12-31T23:59:59Z"));
  }

  @Test
  void repeatedReactivationIsIdempotent() {
    var service = createService(new Effects());
    service.assignAtCreation("reactivate", 1L, 24, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.suspend("reactivate");
    service.reactivate("reactivate");
    var first = service.snapshot("reactivate").orElseThrow();
    assertThat(service.reactivate("reactivate")).isTrue();
    assertThat(service.snapshot("reactivate").orElseThrow()).isEqualTo(first);
  }

  @Test
  void concurrentCreationKeepsExactlyOneImmutableSnapshot() throws Exception {
    var service = createService(new Effects());
    try (var pool = java.util.concurrent.Executors.newFixedThreadPool(8)) {
      var start = new java.util.concurrent.CountDownLatch(1);
      var futures = new java.util.ArrayList<java.util.concurrent.Future<?>>();
      for (int i = 1; i <= 8; i++) {
        final int months = i;
        futures.add(
            pool.submit(
                () -> {
                  try {
                    start.await();
                  } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                  }
                  service.assignAtCreation(
                      "race", 1L, months, months, Instant.parse("2026-01-01T00:00:00Z"));
                }));
      }
      start.countDown();
      for (var future : futures) future.get(10, java.util.concurrent.TimeUnit.SECONDS);
    }
    var first = service.snapshot("race").orElseThrow();
    service.assignAtCreation("race", 1L, 24, 24, Instant.parse("2026-01-01T00:00:00Z"));
    assertThat(service.snapshot("race").orElseThrow()).isEqualTo(first);
  }

  @Test
  void failedEffectsRemainDiagnosableAfterSuccessfulRetry() {
    var service =
        createService(
            new Effects() {
              public boolean delete(String id) {
                return false;
              }
            });
    service.assignAtCreation("audit", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.scan(false);
    createServiceWithoutReset(new Effects()).scan(false);
    assertThat(service.journal("audit").stream().map(AccountInactivityService.Attempt::outcome))
        .contains("UNCONFIRMED", "CONFIRMED");
    assertThat(service.snapshot("audit").orElseThrow().attempts()).isEqualTo(2);
  }

  @Test
  void concurrentScansPerformOneConfirmedEffect() throws Exception {
    var entered = new java.util.concurrent.CountDownLatch(1);
    var release = new java.util.concurrent.CountDownLatch(1);
    var actions = new java.util.concurrent.atomic.AtomicInteger();
    var service =
        createService(
            new Effects() {
              public boolean delete(String id) {
                actions.incrementAndGet();
                entered.countDown();
                try {
                  if (!release.await(10, java.util.concurrent.TimeUnit.SECONDS))
                    throw new IllegalStateException("Timed out");
                } catch (InterruptedException e) {
                  throw new RuntimeException(e);
                }
                return true;
              }
            });
    service.assignAtCreation("workers", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    try (var pool = java.util.concurrent.Executors.newFixedThreadPool(2)) {
      var first = pool.submit(() -> service.scan(false));
      assertThat(entered.await(10, java.util.concurrent.TimeUnit.SECONDS)).isTrue();
      var second = pool.submit(() -> service.scan(false));
      release.countDown();
      first.get(10, java.util.concurrent.TimeUnit.SECONDS);
      second.get(10, java.util.concurrent.TimeUnit.SECONDS);
    }
    assertThat(actions.get()).isEqualTo(1);
    assertThat(service.snapshot("workers").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.DELETED);
  }

  @Test
  void committedActivityWinsAgainstConcurrentExpiryClaim() throws Exception {
    var actions = new java.util.concurrent.atomic.AtomicInteger();
    var service =
        createService(
            new Effects() {
              public boolean delete(String id) {
                actions.incrementAndGet();
                return true;
              }
            });
    service.assignAtCreation("activity", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    var ds = new DriverManagerDataSource("jdbc:h2:mem:lifecycle;DB_CLOSE_DELAY=-1", "sa", "");
    var template =
        new org.springframework.transaction.support.TransactionTemplate(
            new DataSourceTransactionManager(ds));
    var sameTransactionService =
        new AccountInactivityService(
            new JdbcTemplate(ds),
            new DataSourceTransactionManager(ds),
            Clock.fixed(Instant.parse("2026-02-01T00:00:00Z"), ZoneOffset.UTC),
            new Effects());
    var updated = new java.util.concurrent.CountDownLatch(1);
    var commit = new java.util.concurrent.CountDownLatch(1);
    try (var pool = java.util.concurrent.Executors.newFixedThreadPool(2)) {
      var activity =
          pool.submit(
              () ->
                  template.executeWithoutResult(
                      ignored -> {
                        sameTransactionService.recordActivity(
                            "activity", Instant.parse("2026-01-31T00:00:00Z"));
                        updated.countDown();
                        try {
                          commit.await(10, java.util.concurrent.TimeUnit.SECONDS);
                        } catch (InterruptedException e) {
                          throw new RuntimeException(e);
                        }
                      }));
      assertThat(updated.await(10, java.util.concurrent.TimeUnit.SECONDS)).isTrue();
      var scan = pool.submit(() -> service.scan(false));
      commit.countDown();
      activity.get(10, java.util.concurrent.TimeUnit.SECONDS);
      scan.get(10, java.util.concurrent.TimeUnit.SECONDS);
    }
    assertThat(actions.get()).isZero();
    assertThat(service.snapshot("activity").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("2026-02-28T00:00:00Z"));
  }

  @Test
  void futureActivityCannotPostponeExpiryBeyondObservedServerTime() {
    var service = createService(new Effects());
    service.assignAtCreation("future", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.recordActivity("future", Instant.parse("2099-01-01T00:00:00Z"));
    assertThat(service.snapshot("future").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("2026-03-01T00:00:00Z"));
  }

  @Test
  void unavailableRolesStayActiveAndProduceDiagnosticInsteadOfDestructiveGuess() {
    var service =
        createService(
            new Effects() {
              public Set<Role> currentRoles(String id) {
                return Set.of(Role.UNKNOWN);
              }

              public boolean delete(String id) {
                throw new AssertionError("Must not delete unknown roles");
              }
            });
    service.assignAtCreation("unknown", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.scan(false);
    assertThat(service.snapshot("unknown").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.ACTIVE);
    assertThat(service.snapshot("unknown").orElseThrow().lastError())
        .isEqualTo("ROLE_DISCOVERY_FAILED");
  }

  @Test
  void finalRoleChangeConvertsDeletionIntoSuspension() {
    var service =
        createService(
            new Effects() {
              public boolean delete(String id) {
                throw new AccountInactivityEffectException(
                    AccountInactivityEffectException.Target.KEYCLOAK,
                    AccountInactivityEffectException.Code.ROLE_CHANGED);
              }
            });
    service.assignAtCreation("changed", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.scan(false);
    assertThat(service.snapshot("changed").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDING);
    service.scan(false);
    assertThat(service.snapshot("changed").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDED);
    assertThat(service.journal("changed").stream().map(AccountInactivityService.Attempt::outcome))
        .contains("ROLE_CHANGED", "CONFIRMED");
  }

  @Test
  void admissionRejectsMissingAndSuspendedAccountsAndAcceptsActiveConfirmedActivity() {
    var service = createService(new Effects());
    assertThat(service.admit("missing", null)).isFalse();
    service.assignAtCreation("admit", 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    assertThat(service.admit("admit", Instant.parse("2026-02-01T00:00:00Z"))).isTrue();
    assertThat(service.snapshot("admit").orElseThrow().dueAt())
        .isEqualTo(Instant.parse("2026-03-01T00:00:00Z"));
    service.suspend("admit");
    assertThat(service.admit("admit", Instant.parse("2026-02-01T00:00:00Z"))).isFalse();
  }

  @Test
  void suspendedIdentityCannotMutateRolesWhileNewIdentityMayReceiveInitialRoles() {
    var service = createService(new Effects());
    var writes = new java.util.concurrent.atomic.AtomicInteger();
    service.withRoleMutation("new", writes::incrementAndGet);
    service.assignAtCreation("roles", 1L, 24, 1, Instant.parse("2026-01-01T00:00:00Z"));
    service.withRoleMutation("roles", writes::incrementAndGet);
    service.suspend("roles");
    org.assertj.core.api.Assertions.assertThatThrownBy(
            () -> service.withRoleMutation("roles", writes::incrementAndGet))
        .isInstanceOf(IllegalStateException.class);
    assertThat(writes.get()).isEqualTo(2);
  }

  @Test
  void candidateReportShowsCurrentRoleActionAndIsolatesRoleLookupFailure() {
    var service =
        createService(
            new Effects() {
              public Set<Role> currentRoles(String id) {
                if (id.equals("a")) return Set.of(Role.ASKER);
                if (id.equals("b")) return Set.of(Role.ASKER, Role.CONSULTANT);
                throw new IllegalStateException("Remote unavailable");
              }
            });
    for (var id : java.util.List.of("a", "b", "c"))
      service.assignAtCreation(id, 1L, 1, 1, Instant.parse("2026-01-01T00:00:00Z"));
    assertThat(
            service.candidateReport("", 3).stream()
                .map(AccountInactivityService.Candidate::plannedAction))
        .containsExactly(
            AccountInactivityService.PlannedAction.DELETE,
            AccountInactivityService.PlannedAction.SUSPEND,
            AccountInactivityService.PlannedAction.BLOCKED);
    assertThat(service.candidateReport("a", 1).getFirst().snapshot().identityId()).isEqualTo("b");
    assertThat(service.snapshot("a").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.ACTIVE);
  }

  @Test
  void durableClaimSurvivesAnOuterCallerRollback() {
    createService(new Effects());
    var ds = new DriverManagerDataSource("jdbc:h2:mem:lifecycle;DB_CLOSE_DELAY=-1", "sa", "");
    var manager = new DataSourceTransactionManager(ds);
    var service =
        new AccountInactivityService(
            new JdbcTemplate(ds),
            manager,
            Clock.fixed(Instant.parse("2026-02-01T00:00:00Z"), ZoneOffset.UTC),
            new Effects() {
              public boolean suspend(String id) {
                return false;
              }
            });
    service.assignAtCreation("rollback", 1L, 24, 1, Instant.parse("2026-01-01T00:00:00Z"));
    var outer = new org.springframework.transaction.support.TransactionTemplate(manager);
    org.assertj.core.api.Assertions.assertThatThrownBy(
            () ->
                outer.executeWithoutResult(
                    ignored -> {
                      service.suspend("rollback");
                      throw new IllegalStateException("caller rollback");
                    }))
        .isInstanceOf(IllegalStateException.class);
    assertThat(service.snapshot("rollback").orElseThrow().status())
        .isEqualTo(AccountInactivityService.Status.SUSPENDING);
  }

  private AccountInactivityService createService(Effects effects) {
    var jdbc =
        new JdbcTemplate(
            new DriverManagerDataSource("jdbc:h2:mem:lifecycle;DB_CLOSE_DELAY=-1", "sa", ""));
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity");
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity_journal");
    jdbc.execute(
        "CREATE TABLE account_inactivity_journal(journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY,identity_id VARCHAR(36),action VARCHAR(30),target VARCHAR(30),outcome"
            + " VARCHAR(40),created_at TIMESTAMP(6))");
    jdbc.execute(
        "CREATE TABLE account_inactivity(identity_id VARCHAR(36) PRIMARY KEY,tenant_id"
            + " BIGINT,assigned_months INT NOT NULL,revision BIGINT NOT NULL,last_activity"
            + " TIMESTAMP(6) NOT NULL,due_at TIMESTAMP(6) NOT NULL,status VARCHAR(20) NOT"
            + " NULL,last_error VARCHAR(1000),attempts INT DEFAULT 0 NOT NULL)");
    return createServiceWithoutReset(effects);
  }

  private AccountInactivityService createServiceWithoutReset(Effects effects) {
    var ds = new DriverManagerDataSource("jdbc:h2:mem:lifecycle;DB_CLOSE_DELAY=-1", "sa", "");
    return new AccountInactivityService(
        new JdbcTemplate(ds),
        new DataSourceTransactionManager(ds),
        Clock.fixed(Instant.parse("2026-02-01T00:00:00Z"), ZoneOffset.UTC),
        effects);
  }

  static class Effects implements AccountInactivityEffects {
    public Set<Role> currentRoles(String id) {
      return Set.of(Role.ASKER);
    }

    public boolean delete(String id) {
      return true;
    }

    public boolean suspend(String id) {
      return true;
    }

    public boolean reactivate(String id) {
      return true;
    }
  }
}
