version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    target-branch: pre-dev
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: pre-dev
    open-pull-requests-limit: 5
