package de.caritas.cob.userservice.api.service.notification;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;

import com.neovisionaries.i18n.LanguageCode;
import de.caritas.cob.userservice.api.model.Chat;
import de.caritas.cob.userservice.api.model.Consultant;
import de.caritas.cob.userservice.api.model.ConversationType;
import de.caritas.cob.userservice.api.model.GroupChatParticipant;
import de.caritas.cob.userservice.api.model.User;
import de.caritas.cob.userservice.api.model.UserChat;
import de.caritas.cob.userservice.api.port.out.ConsultantRepository;
import de.caritas.cob.userservice.api.port.out.GroupChatParticipantRepository;
import de.caritas.cob.userservice.api.port.out.UserChatRepository;
import de.caritas.cob.userservice.api.port.out.UserRepository;
import de.caritas.cob.userservice.api.service.email.OrisoEmailRenderer;
import de.caritas.cob.userservice.api.workflow.accountinactivity.AccountInactivityEffects;
import de.caritas.cob.userservice.api.workflow.accountinactivity.AccountInactivityService;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Optional;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

@ExtendWith(MockitoExtension.class)
class GroupAppointmentEmailRecipientServiceTest {
  @Mock UserRepository users;
  @Mock ConsultantRepository consultants;
  @Mock UserChatRepository userChats;
  @Mock GroupChatParticipantRepository counselors;
  @Mock AccountInactivityEffects accountEffects;

  private JdbcTemplate lifecycleDatabase;
  private AccountInactivityService lifecycle;

  @BeforeEach
  void lifecycle() {
    var dataSource =
        new DriverManagerDataSource(
            "jdbc:h2:mem:group-mail-recipient-lifecycle;DB_CLOSE_DELAY=-1", "sa", "");
    lifecycleDatabase = new JdbcTemplate(dataSource);
    lifecycleDatabase.execute(
        "CREATE TABLE account_inactivity(identity_id VARCHAR(36) PRIMARY KEY,tenant_id"
            + " BIGINT,assigned_months INT NOT NULL,revision BIGINT NOT NULL,last_activity"
            + " TIMESTAMP(6) NOT NULL,due_at TIMESTAMP(6) NOT NULL,status VARCHAR(20) NOT"
            + " NULL,last_error VARCHAR(1000),attempts INT DEFAULT 0 NOT NULL)");
    lifecycleDatabase.execute(
        "CREATE TABLE account_inactivity_journal(journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY"
            + " PRIMARY KEY,identity_id VARCHAR(36),action VARCHAR(30),target VARCHAR(30),outcome"
            + " VARCHAR(40),created_at TIMESTAMP(6))");
    lifecycle =
        new AccountInactivityService(
            lifecycleDatabase,
            new DataSourceTransactionManager(dataSource),
            Clock.fixed(Instant.parse("2026-10-08T00:00:00Z"), ZoneOffset.UTC),
            accountEffects);
  }

  @AfterEach
  void closeLifecycleDatabase() {
    lifecycleDatabase.execute("SHUTDOWN");
  }

  private GroupAppointmentEmailRecipientService service() {
    return new GroupAppointmentEmailRecipientService(
        users, consultants, userChats, counselors, lifecycle, ".invalid");
  }

  private static Chat group() {
    Chat chat = new Chat();
    chat.setId(42L);
    chat.setConversationType(ConversationType.SELF_HELP);
    return chat;
  }

  @Test
  void resolvesAnEligibleParticipantWithTheirOwnTone() {
    Chat group = group();
    User user = new User();
    user.setUserId("seeker-1");
    user.setEmail("seeker@example.org");
    user.setLanguageCode(LanguageCode.de);
    user.setLanguageFormal(false);
    user.setNotificationsEnabled(true);
    user.setNotificationsSettings("{\"appointmentNotificationEnabled\":true}");
    when(users.findByUserIdAndDeleteDateIsNull("seeker-1")).thenReturn(Optional.of(user));
    when(userChats.findByChatAndUser(group, user))
        .thenReturn(Optional.of(UserChat.builder().chat(group).user(user).build()));

    assertThat(
            service()
                .resolve(group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .contains(
            new GroupAppointmentEmailRecipientService.Recipient(
                "seeker-1", "seeker@example.org", OrisoEmailRenderer.Tone.DE_INFORMAL));
  }

  @Test
  void resolvesAnInvitedCounselorFromAnotherTenantOnlyWhileTheirCurrentAccountIsActive() {
    Chat group = group();
    group.setConversationType(null);
    group.setRepeatCount(2);
    Consultant owner = new Consultant();
    owner.setTenantId(5L);
    group.setChatOwner(owner);
    Consultant counselor = new Consultant();
    counselor.setId("counselor-1");
    counselor.setTenantId(99L);
    counselor.setEmail("counselor@example.org");
    counselor.setLanguageCode(LanguageCode.fr);
    counselor.setNotificationsEnabled(true);
    counselor.setNotificationsSettings("{\"appointmentNotificationEnabled\":true}");
    when(consultants.findByIdAndDeleteDateIsNull("counselor-1")).thenReturn(Optional.of(counselor));
    when(counselors.findBySeriesIdAndConsultantId(42L, "counselor-1"))
        .thenReturn(Optional.of(new GroupChatParticipant()));
    lifecycle.assignAtCreation("counselor-1", 99L, 12, 1L, Instant.parse("2026-10-01T00:00:00Z"));
    var resolver = service();
    var expected =
        new GroupAppointmentEmailRecipientService.Recipient(
            "counselor-1", "counselor@example.org", OrisoEmailRenderer.Tone.FR);

    assertThat(
            resolver.resolve(
                group, GroupAppointmentEmailRecipientService.Role.COUNSELOR, "counselor-1"))
        .contains(expected);

    when(accountEffects.suspend("counselor-1")).thenReturn(true);
    assertThat(lifecycle.suspend("counselor-1")).isTrue();
    assertThat(counselor.getDeleteDate()).isNull();
    assertThat(
            resolver.resolve(
                group, GroupAppointmentEmailRecipientService.Role.COUNSELOR, "counselor-1"))
        .isEmpty();

    when(accountEffects.reactivate("counselor-1")).thenReturn(true);
    assertThat(lifecycle.reactivate("counselor-1")).isTrue();
    assertThat(
            resolver.resolve(
                group, GroupAppointmentEmailRecipientService.Role.COUNSELOR, "counselor-1"))
        .contains(expected);
  }

  @Test
  void rejectsDisabledOrDummyParticipantAddresses() {
    Chat group = group();
    User user = new User();
    user.setUserId("seeker-1");
    user.setEmail("seeker@system.invalid");
    user.setLanguageCode(LanguageCode.en);
    user.setNotificationsEnabled(true);
    user.setNotificationsSettings("{\"appointmentNotificationEnabled\":true}");
    when(users.findByUserIdAndDeleteDateIsNull("seeker-1")).thenReturn(Optional.of(user));
    when(userChats.findByChatAndUser(group, user))
        .thenReturn(Optional.of(UserChat.builder().chat(group).user(user).build()));

    assertThat(
            service()
                .resolve(group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isEmpty();
    user.setEmail("seeker@example.org");
    user.setNotificationsSettings("{\"appointmentNotificationEnabled\":false}");
    assertThat(
            service()
                .resolve(group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isEmpty();
  }

  @Test
  void suspendedParticipantWithNoDeleteDateCannotReceiveGroupMail() {
    Chat group = group();
    User user = new User();
    user.setUserId("seeker-1");
    user.setEmail("seeker@example.org");
    user.setLanguageCode(LanguageCode.en);
    user.setNotificationsEnabled(true);
    user.setNotificationsSettings("{\"appointmentNotificationEnabled\":true}");
    when(users.findByUserIdAndDeleteDateIsNull("seeker-1")).thenReturn(Optional.of(user));
    when(userChats.findByChatAndUser(group, user))
        .thenReturn(Optional.of(UserChat.builder().chat(group).user(user).build()));
    lifecycle.assignAtCreation("seeker-1", 5L, 12, 1L, Instant.parse("2026-10-01T00:00:00Z"));
    when(accountEffects.suspend("seeker-1")).thenReturn(true);
    assertThat(lifecycle.suspend("seeker-1")).isTrue();
    assertThat(lifecycle.snapshot("seeker-1"))
        .hasValueSatisfying(
            account ->
                assertThat(account.status()).isEqualTo(AccountInactivityService.Status.SUSPENDED));
    assertThat(user.getDeleteDate()).isNull();

    assertThat(
            service()
                .resolve(group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isEmpty();
  }

  @Test
  void internalGroupsAreNeverEmailSources() {
    Chat internal = group();
    internal.setConversationType(ConversationType.INTERNAL_GROUP);
    assertThat(
            service()
                .resolve(
                    internal, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isEmpty();
  }

  @Test
  void aUserWhoLeftTheGroupCannotReceiveItsMail() {
    Chat group = group();
    User user = new User();
    user.setUserId("seeker-1");
    when(users.findByUserIdAndDeleteDateIsNull("seeker-1")).thenReturn(Optional.of(user));
    when(userChats.findByChatAndUser(group, user)).thenReturn(Optional.empty());

    assertThat(
            service()
                .resolve(group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isEmpty();
  }

  @Test
  void anUnknownLanguageDoesNotSilentlyChooseAnotherTemplate() {
    Chat group = group();
    User user = new User();
    user.setUserId("seeker-1");
    user.setEmail("seeker@example.org");
    user.setNotificationsEnabled(true);
    user.setNotificationsSettings("{\"appointmentNotificationEnabled\":true}");
    when(users.findByUserIdAndDeleteDateIsNull("seeker-1")).thenReturn(Optional.of(user));
    when(userChats.findByChatAndUser(group, user))
        .thenReturn(Optional.of(UserChat.builder().chat(group).user(user).build()));

    assertThatThrownBy(
            () ->
                service()
                    .resolve(
                        group, GroupAppointmentEmailRecipientService.Role.PARTICIPANT, "seeker-1"))
        .isInstanceOf(IllegalArgumentException.class)
        .hasMessageContaining("Recipient language is missing");
  }
}
