package de.caritas.cob.userservice.api.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import de.caritas.cob.userservice.api.adapters.web.controller.AccountInactivityController;
import de.caritas.cob.userservice.api.adapters.web.controller.interceptor.AccountInactivityAccessFilter;
import de.caritas.cob.userservice.api.workflow.accountinactivity.AccountInactivityService;
import java.time.*;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

class AccountInactivityHttpTest {
  @Test
  void backgroundReadsDoNotExtendThePeriodButDeliberateActivityDoes() throws Exception {
    var ds = new DriverManagerDataSource("jdbc:h2:mem:inactivityhttp;DB_CLOSE_DELAY=-1", "sa", "");
    var jdbc = new JdbcTemplate(ds);
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity");
    jdbc.execute(
        "CREATE TABLE account_inactivity(identity_id VARCHAR(36) PRIMARY KEY,tenant_id BIGINT,assigned_months INT NOT NULL,revision BIGINT NOT NULL,last_activity TIMESTAMP(6) NOT NULL,due_at TIMESTAMP(6) NOT NULL,status VARCHAR(20) NOT NULL,last_error VARCHAR(1000),attempts INT DEFAULT 0 NOT NULL)");
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS account_inactivity_journal(journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,identity_id VARCHAR(36),action VARCHAR(30),target VARCHAR(30),outcome VARCHAR(40),created_at TIMESTAMP(6))");
    var clock = Clock.fixed(Instant.parse("2026-09-16T10:00:00Z"), ZoneOffset.UTC);
    var lifecycle =
        new AccountInactivityService(
            jdbc,
            new DataSourceTransactionManager(ds),
            clock,
            new AccountInactivityEnrollmentTest.ExternalEffects());
    var login = Instant.parse("2026-09-01T10:00:00Z");
    lifecycle.assignAtCreation("person", 1L, 24, 0, login);
    var jwt =
        Jwt.withTokenValue("test-token")
            .header("alg", "RS256")
            .subject("person")
            .claim("tenantId", 1)
            .claim("auth_time", login.getEpochSecond())
            .claim("realm_access", Map.of("roles", List.of("user")))
            .build();
    var auth = new JwtAuthenticationToken(jwt);
    var mvc =
        MockMvcBuilders.standaloneSetup(
                new AccountInactivityController(
                    lifecycle,
                    clock,
                    new org.springframework.beans.factory.support.StaticListableBeanFactory()
                        .getBeanProvider(
                            de.caritas.cob.userservice.api.workflow.accountinactivity
                                .AccountInactivityBootstrap.class)))
            .addFilters(new AccountInactivityAccessFilter(lifecycle))
            .build();
    mvc.perform(get("/users/account-inactivity").principal(auth)).andExpect(status().isOk());
    assertThat(lifecycle.snapshot("person").orElseThrow().lastActivity()).isEqualTo(login);
    mvc.perform(post("/users/account-inactivity/activity").principal(auth))
        .andExpect(status().isNoContent());
    assertThat(lifecycle.snapshot("person").orElseThrow().lastActivity())
        .isEqualTo(clock.instant());
    mvc.perform(get("/useradmin/account-inactivity/candidates").principal(auth))
        .andExpect(status().isForbidden());
    mvc.perform(get("/useradmin/account-inactivity/inventory").principal(auth))
        .andExpect(status().isForbidden());
    assertThat(lifecycle.suspend("person")).isTrue();
    mvc.perform(get("/users/account-inactivity").principal(auth)).andExpect(status().isForbidden());
    mvc.perform(post("/users/account-inactivity/activity").principal(auth))
        .andExpect(status().isForbidden());
    lifecycle.assignAtCreation("platform-admin", 0L, 24, 0, clock.instant());
    var admin =
        new JwtAuthenticationToken(
            Jwt.withTokenValue("test-admin-token")
                .header("alg", "RS256")
                .subject("platform-admin")
                .claim("tenantId", 0)
                .claim("realm_access", Map.of("roles", List.of("agency-admin", "tenant-admin")))
                .build());
    mvc.perform(post("/useradmin/account-inactivity/person/reactivate").principal(admin))
        .andExpect(status().isNoContent());
    mvc.perform(get("/users/account-inactivity").principal(auth)).andExpect(status().isOk());
    var mixedTechnical =
        new JwtAuthenticationToken(
            Jwt.withTokenValue("mixed-token")
                .header("alg", "RS256")
                .subject("missing-admin")
                .claim("tenantId", 0)
                .claim("realm_access", Map.of("roles", List.of("technical")))
                .claim("resource_access", Map.of("oriso", Map.of("roles", List.of("user-admin"))))
                .build());
    mvc.perform(get("/users/account-inactivity/access").principal(mixedTechnical))
        .andExpect(status().isForbidden());
  }
}
