package de.caritas.cob.userservice.api.service;

import static org.assertj.core.api.Assertions.*;

import de.caritas.cob.userservice.api.port.out.IdentityRoleUpdater;
import de.caritas.cob.userservice.api.workflow.accountinactivity.AccountInactivityService;
import java.time.*;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.Test;
import org.springframework.aop.aspectj.annotation.AspectJProxyFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class AccountInactivityRoleChangeTest {
  @Test
  void claimedIdentityCannotAcquireRolesUntilReactivated() {
    var ds = new DriverManagerDataSource("jdbc:h2:mem:rolechange;DB_CLOSE_DELAY=-1", "sa", "");
    var jdbc = new JdbcTemplate(ds);
    jdbc.execute("DROP TABLE IF EXISTS account_inactivity");
    jdbc.execute(
        "CREATE TABLE account_inactivity(identity_id VARCHAR(36) PRIMARY KEY,tenant_id BIGINT,assigned_months INT NOT NULL,revision BIGINT NOT NULL,last_activity TIMESTAMP(6) NOT NULL,due_at TIMESTAMP(6) NOT NULL,status VARCHAR(20) NOT NULL,last_error VARCHAR(1000),attempts INT DEFAULT 0 NOT NULL)");
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS account_inactivity_journal(journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,identity_id VARCHAR(36),action VARCHAR(30),target VARCHAR(30),outcome VARCHAR(40),created_at TIMESTAMP(6))");
    var clock = Clock.fixed(Instant.parse("2026-09-16T10:00:00Z"), ZoneOffset.UTC);
    var lifecycle =
        new AccountInactivityService(
            jdbc,
            new DataSourceTransactionManager(ds),
            clock,
            new AccountInactivityEnrollmentTest.ExternalEffects());
    lifecycle.assignAtCreation("person", 1L, 24, 0, clock.instant());
    var remoteWrites = new AtomicInteger();
    IdentityRoleUpdater remote = (id, roles) -> remoteWrites.incrementAndGet();
    var proxyFactory = new AspectJProxyFactory(remote);
    proxyFactory.addAspect(new AccountInactivityRoleMutationAspect(lifecycle));
    IdentityRoleUpdater gateway = proxyFactory.getProxy();
    gateway.ensureRoles("person", List.of("user-admin"));
    assertThat(remoteWrites.get()).isEqualTo(1);
    lifecycle.suspend("person");
    assertThatThrownBy(() -> gateway.ensureRoles("person", List.of("consultant")))
        .isInstanceOf(org.springframework.web.server.ResponseStatusException.class);
    assertThat(remoteWrites.get()).isEqualTo(1);
  }
}
