package de.caritas.cob.userservice.api.service.email;

import static org.apache.commons.lang3.StringUtils.isNotBlank;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.neovisionaries.i18n.LanguageCode;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

/**
 * Renders a transactional e-mail from the ORISO e-mail design system.
 *
 * <p>The templates under {@code src/main/resources/emails} are generated by the design system in
 * ORISO-Frontend and copied here by {@code scripts/sync-email-templates.sh} — they are never edited
 * in this repository. Storybook renders the same content model, so what a reviewer approves there
 * is what this class sends. See ADR-020 in ORISO-Frontend.
 *
 * <p>This service consumes the {@code plain} dialect, which is deliberately not a template engine:
 * the substitution below is the whole of it. Anything cleverer would be a second renderer, and a
 * second renderer is how a mail starts disagreeing with its own design.
 */
@Slf4j
@Component
public class OrisoEmailRenderer {

  private static final String BASE = "/emails";

  private static final Pattern PLACEHOLDER = Pattern.compile("\\{\\{\\s*([\\w.]+)\\s*}}");

  /**
   * The header's logo cell. The templates carry a single {@code {{logoCell}}} token where the
   * design system places the logo, and this is the markup that token expands to when a logo URL is
   * configured. When {@code logoUrl} is blank the token expands to nothing at all: an {@code <img
   * src="">} renders as a broken-image icon next to the platform name, so the text wordmark has to
   * carry the header alone. The dialect has no conditional syntax — this constant is the one
   * conditional the mails need, and it stays in the renderer so the markup remains e-mail-client
   * table markup reviewed together with the templates.
   */
  private static final String LOGO_CELL =
      "<td width=\"36\" valign=\"middle\" style=\"width:36px;padding-right:12px;\">"
          + "<img src=\"{{logoUrl}}\" width=\"36\" height=\"36\" alt=\"{{platformName}}\""
          + " style=\"display:block;width:36px;height:36px;border:0;border-radius:8px;\"></td>";

  private final Map<String, String> templateCache = new ConcurrentHashMap<>();

  private final JsonNode catalogue;

  public OrisoEmailRenderer() {
    this.catalogue = loadCatalogue();
  }

  /** Both MIME parts plus the subject, ready to hand to a {@code MimeMessage}. */
  public record RenderedEmail(String subject, String html, String text) {}

  /**
   * Tone variant. German ships twice because the address form is a per-tenant decision; this
   * service has no tenant tone setting yet, so German resolves to the formal variant.
   */
  public enum Tone {
    DE_FORMAL("de-sie"),
    DE_INFORMAL("de-du"),
    EN("en");

    private final String directory;

    Tone(String directory) {
      this.directory = directory;
    }

    public String directory() {
      return directory;
    }

    public static Tone of(LanguageCode languageCode) {
      return languageCode != null && "en".equalsIgnoreCase(languageCode.name()) ? EN : DE_FORMAL;
    }
  }

  /**
   * Renders one mail.
   *
   * @param templateId an id from {@code catalogue.json}, e.g. {@code anmeldelink}
   * @param values one entry per {@code {{placeholder}}} the template needs; a missing key leaves
   *     the placeholder visible rather than blanking it, because a visible {@code {{foo}}} is a bug
   *     report and a silent blank is not
   */
  public RenderedEmail render(String templateId, Tone tone, Map<String, String> values) {
    values = withOccasionOnUnsubscribeLink(templateId, values);
    String html = substitute(withLogoCell(read(templateId, tone, "html"), values), values, true);
    String text = substitute(read(templateId, tone, "txt"), values, false);
    String subject = substitute(subjectOf(templateId, tone), values, false);
    return new RenderedEmail(subject, html, text);
  }

  /**
   * Tells the unsubscribe link which mail it came from.
   *
   * <p>A footer link that lands on a settings screen full of switches leaves the recipient to work
   * out which one produced the mail in their hand. Carrying the occasion lets the screen focus the
   * right switch — see ORISO-Frontend#872, which is the other half of this.
   *
   * <p>A security or legal mail has no unsubscribe link at all, so there is nothing to decorate.
   */
  private Map<String, String> withOccasionOnUnsubscribeLink(
      String templateId, Map<String, String> values) {
    String link = values.get("unsubscribeUrl");
    if (!isUnsubscribable(templateId) || link == null || link.isBlank()) {
      return values;
    }
    Map<String, String> decorated = new LinkedHashMap<>(values);
    decorated.put("unsubscribeUrl", link + (link.contains("?") ? "&" : "?") + "mail=" + templateId);
    return decorated;
  }

  /** The subject line, from the generated catalogue rather than from the document. */
  public String subjectOf(String templateId, Tone tone) {
    JsonNode node =
        catalogue
            .path("mails")
            .path(templateId)
            .path("tones")
            .path(tone.directory())
            .path("subject");
    if (node.isMissingNode() || !isNotBlank(node.asText())) {
      throw new IllegalStateException(
          "no subject for e-mail template '" + templateId + "' in tone " + tone.directory());
    }
    return node.asText();
  }

  /** Whether the footer of this occasion offers an unsubscribe link (ADR-019). */
  public boolean isUnsubscribable(String templateId) {
    return catalogue.path("mails").path(templateId).path("unsubscribable").asBoolean(true);
  }

  private String read(String templateId, Tone tone, String extension) {
    String path = BASE + "/" + tone.directory() + "/" + templateId + "." + extension;
    return templateCache.computeIfAbsent(path, this::readResource);
  }

  private String readResource(String path) {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(path)) {
      if (in == null) {
        throw new IllegalStateException(
            "e-mail template " + path + " is missing — run scripts/sync-email-templates.sh");
      }
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read e-mail template " + path, exception);
    }
  }

  private JsonNode loadCatalogue() {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(BASE + "/catalogue.json")) {
      if (in == null) {
        throw new IllegalStateException(
            "emails/catalogue.json is missing — run scripts/sync-email-templates.sh");
      }
      return new ObjectMapper().readTree(in);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read emails/catalogue.json", exception);
    }
  }

  /**
   * Expands {@code {{logoCell}}} to the logo image cell, or to nothing when no logo URL is
   * configured. Runs before {@link #substitute}, so the {@code {{logoUrl}}} and {@code
   * {{platformName}}} inside the expanded markup are filled — and escaped — like any other
   * placeholder.
   */
  private String withLogoCell(String html, Map<String, String> values) {
    return html.replace("{{logoCell}}", isNotBlank(values.get("logoUrl")) ? LOGO_CELL : "");
  }

  /**
   * Substitutes {@code {{placeholders}}}.
   *
   * <p>The HTML part escapes markup-significant characters — a counsellor display name or a tenant
   * name is user-controlled input, and it is being written into a document, not into a log line.
   * The text part does not escape, because there is no markup to protect.
   */
  private String substitute(String source, Map<String, String> values, boolean escape) {
    Matcher matcher = PLACEHOLDER.matcher(source);
    StringBuilder out = new StringBuilder();
    while (matcher.find()) {
      String replacement = values.get(matcher.group(1));
      if (replacement == null) {
        matcher.appendReplacement(out, Matcher.quoteReplacement(matcher.group()));
        continue;
      }
      matcher.appendReplacement(
          out, Matcher.quoteReplacement(escape ? escapeHtml(replacement) : replacement));
    }
    matcher.appendTail(out);
    return out.toString();
  }

  private static String escapeHtml(String value) {
    return HtmlUtils.htmlEscape(value, StandardCharsets.UTF_8.name());
  }
}
