package de.caritas.cob.userservice.api.service.email;

import static org.apache.commons.lang3.StringUtils.isNotBlank;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.neovisionaries.i18n.LanguageCode;
import de.caritas.cob.userservice.api.service.email.layout.EmailColors;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

/**
 * Renders a transactional e-mail from the ORISO e-mail design system.
 *
 * <p>The templates under {@code src/main/resources/emails} are generated by the design system in
 * ORISO-Frontend and copied here by {@code scripts/sync-email-templates.sh} — they are never edited
 * in this repository. Storybook renders the same content model, so what a reviewer approves there
 * is what this class sends. See ADR-020 in ORISO-Frontend.
 *
 * <p>One exception, and it is temporary: {@code einladung-freitext} — the frame around an
 * operator-authored invite text — was added here first, because the invite mail had to leave its
 * hand-written layout before the design system had a generic message template. The sync script
 * refuses to complete while that template is missing from the generated set, so the day it is added
 * in ORISO-Frontend this repository stops being its home without anyone noticing a gap.
 *
 * <p>This service consumes the {@code plain} dialect, which is deliberately not a template engine:
 * the substitution below is the whole of it. Anything cleverer would be a second renderer, and a
 * second renderer is how a mail starts disagreeing with its own design.
 */
@Slf4j
@Component
public class OrisoEmailRenderer {

  private static final String BASE = "/emails";

  private static final Pattern PLACEHOLDER = Pattern.compile("\\{\\{\\s*([\\w.]+)\\s*}}");

  /**
   * The header's logo cell. The templates carry a single {@code {{logoCell}}} token where the
   * design system places the logo, and this is the markup that token expands to when a logo URL is
   * configured. When {@code logoUrl} is blank the token expands to nothing at all: an {@code <img
   * src="">} renders as a broken-image icon next to the platform name, so the text wordmark has to
   * carry the header alone. The platform name always stands in the next cell, so the logo is
   * decorative ({@code alt=""}): a logo that fails to load must not repeat the name beside itself.
   * The dialect has no conditional syntax — this constant is one of the conditionals the mails
   * need, and it stays in the renderer so the markup remains e-mail-client table markup reviewed
   * together with the templates.
   */
  private static final String LOGO_CELL =
      "<td width=\"36\" valign=\"middle\" style=\"width:36px;padding-right:12px;\">"
          + "<img src=\"{{logoUrl}}\" width=\"36\" height=\"36\" alt=\"\""
          + " style=\"display:block;width:36px;height:36px;border:0;border-radius:8px;\"></td>";

  /**
   * The call-to-action button plus the visible copy-paste fallback line, for templates whose action
   * is supplied by the caller rather than fixed in the document (today: {@code
   * einladung-freitext}). The second conditional: a mail whose action URL is absent must not ship a
   * button pointing nowhere, and the dialect cannot express that. Templates with a fixed action —
   * {@code einladung-traeger}, {@code anmeldelink} — carry their own button markup and never see
   * this token.
   */
  private static final String CTA_BLOCK_HTML =
      "<tr><td class=\"sp btn\" align=\"left\" style=\"padding:20px 40px 0px 40px;\">"
          + "<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr>"
          + "<td align=\"center\" bgcolor=\"{{primaryColor}}\""
          + " style=\"background-color:{{primaryColor}};border-radius:999px;\">"
          + "<a href=\"{{actionUrl}}\" style=\"display:inline-block;padding:14px 32px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;"
          + "line-height:20px;font-weight:600;color:#ffffff;text-decoration:none;"
          + "border-radius:999px;\">{{actionLabel}}</a></td></tr></table></td></tr>"
          + "<tr><td class=\"sp\" style=\"padding:16px 40px 0px 40px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;"
          + "line-height:20px;color:#5c5555;word-break:break-word;\">{{fallbackHint}}<br>"
          + "<a href=\"{{actionUrl}}\" style=\"color:{{primaryColor}};text-decoration:underline;"
          + "word-break:break-all;\">{{actionUrl}}</a></td></tr>";

  /** The plain-text half of {@link #CTA_BLOCK_HTML}. */
  private static final String CTA_BLOCK_TEXT = "{{actionLabel}}:\n{{actionUrl}}";

  /**
   * The closing fine print inside the card — divider plus the {@code {{assurance}}} line — for
   * templates whose action is optional ({@code einladung-freitext}). It rides on the same condition
   * as {@link #CTA_BLOCK_HTML}: the line tells the recipient to keep the link to themselves, and a
   * mail without an action has no link to keep. The markup is the design system's {@code
   * emailAssurance} molecule, byte for byte.
   */
  private static final String ASSURANCE_BLOCK_HTML =
      "<tr><td class=\"sp\" style=\"padding:28px 40px 0px 40px;\">"
          + "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\""
          + " border=\"0\"><tr><td height=\"1\" bgcolor=\"#e0dada\""
          + " style=\"height:1px;line-height:1px;font-size:0;\">&nbsp;</td></tr></table></td></tr>"
          + "<tr><td class=\"sp\" style=\"padding:16px 40px 32px 40px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;"
          + "line-height:18px;color:#5c5555;\">{{assurance}}</td></tr>";

  /** The plain-text half of {@link #ASSURANCE_BLOCK_HTML}, divider included like the HTML. */
  private static final String ASSURANCE_BLOCK_TEXT = "-".repeat(64) + "\n{{assurance}}";

  /**
   * The sender organisation's footer values plus the operator's name in the offered-by line. Each
   * is entered in the Admin panel or not at all, and one nobody entered takes its whole line with
   * it (see {@link #withoutBlankSenderLines}).
   */
  private static final String SENDER_KEYS = "orgName|orgAddress|contactLine|operatorName";

  /** A footer element holding only text with a sender placeholder in it. */
  private static final Pattern SENDER_ELEMENT =
      Pattern.compile("<(div|td)(\\s[^>]*)?>([^<]*\\{\\{(?:" + SENDER_KEYS + ")}}[^<]*)</\\1>");

  private static final Pattern SENDER_LINE =
      Pattern.compile("(?m)^[^\\n]*\\{\\{(?:" + SENDER_KEYS + ")}}[^\\n]*(?:\\n|$)");

  private static final Pattern SENDER_PLACEHOLDER =
      Pattern.compile("\\{\\{(" + SENDER_KEYS + ")}}");

  private static final String OPTIONAL_CONTACT_KEYS =
      "consultantPhone|consultantHours|consultantEmail";

  private static final Pattern CONTACT_ROW_HTML =
      Pattern.compile(
          "<tr><td class=\"row-label\"[^>]*>[^<]*</td><td class=\"row-value\"[^>]*>\\{\\{("
              + OPTIONAL_CONTACT_KEYS
              + ")}}</td></tr>");

  private static final Pattern CONTACT_ROW_TEXT =
      Pattern.compile("(?m)^[^\\n]*\\{\\{(" + OPTIONAL_CONTACT_KEYS + ")}}[^\\n]*(?:\\n|$)");

  /**
   * The button label in the generated templates is a hardcoded {@code #ffffff} on a cell filled
   * with {@code {{primaryColor}}}. That only holds for a dark brand colour, so the label colour is
   * rewritten to {@code {{primaryTextColor}}}: white or a dark tone of the brand hue, derived like
   * the web app's {@code --m3-on-primary} (ADR-026 amendment 2026-10-02). The generated templates
   * are never edited here (see the class comment), and the {@code {{ctaBlock}}} markup below must
   * stay byte-identical to the generated fragment (EmailTemplateIntegrityTest); once the generator
   * emits the placeholder itself, this rewrite finds nothing to do.
   */
  private static final Pattern BUTTON_LABEL_COLOUR =
      Pattern.compile(
          "(bgcolor=\"\\{\\{primaryColor}}\"[^>]*>\\s*<a [^>]*?)color:#ffffff",
          Pattern.CASE_INSENSITIVE);

  /**
   * A text link coloured {@code {{primaryColor}}} sits on the white card, where the brand colour
   * itself may be too light to read: it takes {@code {{primaryLinkColor}}}, the brand colour
   * darkened to 4.5:1.
   */
  private static final Pattern BRAND_COLOURED_LINK =
      Pattern.compile("(?<![-\\w])color:\\{\\{primaryColor}}");

  private final Map<String, String> templateCache = new ConcurrentHashMap<>();

  private final JsonNode catalogue;
  private final boolean allowUnreviewedLocales;

  public OrisoEmailRenderer() {
    this(false);
  }

  @Autowired
  public OrisoEmailRenderer(
      @Value("${email.allow-unreviewed-locales:false}") boolean allowUnreviewedLocales) {
    this.catalogue = loadCatalogue();
    this.allowUnreviewedLocales = allowUnreviewedLocales;
  }

  /** Both MIME parts plus the subject, ready to hand to a {@code MimeMessage}. */
  public record RenderedEmail(String subject, String html, String text) {}

  /**
   * Tone variant. German ships twice because the address form is a per-tenant decision; this
   * service has no tenant tone setting yet, so German resolves to the formal variant.
   */
  public enum Tone {
    DE_FORMAL("de-sie"),
    DE_INFORMAL("de-du"),
    EN("en"),
    FR("fr"),
    RU("ru"),
    TI("ti"),
    TR("tr");

    private final String directory;

    Tone(String directory) {
      this.directory = directory;
    }

    public String directory() {
      return directory;
    }

    public static Tone of(LanguageCode languageCode) {
      if (languageCode == null) {
        throw new IllegalArgumentException("Recipient language is missing");
      }
      return switch (languageCode.name().toLowerCase(Locale.ROOT)) {
        case "de" -> DE_FORMAL;
        case "en" -> EN;
        case "fr" -> FR;
        case "ru" -> RU;
        case "ti" -> TI;
        case "tr" -> TR;
        default ->
            throw new IllegalArgumentException(
                "Recipient language has no installed e-mail template: " + languageCode);
      };
    }
  }

  /**
   * Renders one mail.
   *
   * @param templateId an id from {@code catalogue.json}, e.g. {@code anmeldelink}
   * @param values one entry per {@code {{placeholder}}} the template needs; a missing key leaves
   *     the placeholder visible rather than blanking it, because a visible {@code {{foo}}} is a bug
   *     report and a silent blank is not
   */
  public RenderedEmail render(String templateId, Tone tone, Map<String, String> values) {
    return render(templateId, tone, values, Map.of());
  }

  /**
   * Renders one mail, with some slots filled by markup the caller has already produced.
   *
   * <p>{@code fragments} exists for exactly one thing the escaping substitution cannot do: a body
   * that is authored elsewhere and arrives as a finished, already-sanitised HTML fragment (see
   * {@code einladung-freitext}, whose body an operator writes in the Admin panel). Those values are
   * inserted <em>after</em> substitution and are never re-scanned, so a fragment can neither be
   * escaped into visible tag soup nor smuggle a {@code {{placeholder}}} of its own into the
   * document. Everything a template can express without that — every ordinary value — belongs in
   * {@code values}, where it is escaped.
   *
   * @param fragments placeholder name → verbatim replacement; the caller is responsible for the
   *     safety of what it puts in here
   */
  public RenderedEmail render(
      String templateId, Tone tone, Map<String, String> values, Map<String, String> fragments) {
    return renderResolved(templateId, deliveryTone(tone), values, fragments);
  }

  /** Render installed copy for an operator preview; this does not select a delivery locale. */
  public RenderedEmail renderForPreview(String templateId, Tone tone, Map<String, String> values) {
    return renderResolved(templateId, installedPreviewTone(tone), values, Map.of());
  }

  private RenderedEmail renderResolved(
      String templateId, Tone tone, Map<String, String> values, Map<String, String> fragments) {
    values = withDerivedBrandColours(withOccasionOnUnsubscribeLink(templateId, values));
    String html =
        substitute(
            withoutBlankSenderLines(
                withoutBlankContactRows(
                    templateId,
                    withBrandColourRoles(
                        withConditionalBlocks(read(templateId, tone, "html"), values, true)),
                    values,
                    true),
                values,
                true),
            values,
            true);
    String text =
        substitute(
            withoutBlankSenderLines(
                withoutBlankContactRows(
                    templateId,
                    withConditionalBlocks(read(templateId, tone, "txt"), values, false),
                    values,
                    false),
                values,
                false),
            values,
            false);
    String subject = substitute(catalogueCopyExact(templateId, tone, "subject"), values, false);
    return new RenderedEmail(
        insertFragments(subject, fragments),
        insertFragments(html, fragments),
        insertFragments(text, fragments));
  }

  /**
   * Tells the unsubscribe link which mail it came from.
   *
   * <p>A footer link that lands on a settings screen full of switches leaves the recipient to work
   * out which one produced the mail in their hand. Carrying the occasion lets the screen focus the
   * right switch — see ORISO-Frontend#872, which is the other half of this.
   *
   * <p>A security or legal mail has no unsubscribe link at all, so there is nothing to decorate.
   */
  private Map<String, String> withOccasionOnUnsubscribeLink(
      String templateId, Map<String, String> values) {
    String link = values.get("unsubscribeUrl");
    if (!isUnsubscribable(templateId) || link == null || link.isBlank()) {
      return values;
    }
    Map<String, String> decorated = new LinkedHashMap<>(values);
    decorated.put("unsubscribeUrl", link + (link.contains("?") ? "&" : "?") + "mail=" + templateId);
    return decorated;
  }

  /**
   * Supplies {@code primaryTextColor} and {@code primaryLinkColor} from {@code primaryColor} when
   * the caller did not, and writes the normalised {@code primaryColor} back (callers that go
   * through {@link OrisoEmailBrand} always do). A value map without a usable {@code primaryColor}
   * is left alone, so a placeholder stays visible as a bug report instead of a guessed colour.
   */
  private static Map<String, String> withDerivedBrandColours(Map<String, String> values) {
    String primary = EmailColors.normalize(values.get("primaryColor"));
    if (primary == null) {
      return values;
    }
    Map<String, String> derived = new LinkedHashMap<>(values);
    // Write the normalised literal back so a caller's "f8e71c" is valid CSS in the template.
    derived.put("primaryColor", primary);
    derived.putIfAbsent("primaryTextColor", EmailColors.onPrimary(primary));
    derived.putIfAbsent("primaryLinkColor", EmailColors.onLightBackground(primary));
    return derived;
  }

  private static String withBrandColourRoles(String htmlTemplate) {
    String labelled =
        BUTTON_LABEL_COLOUR.matcher(htmlTemplate).replaceAll("$1color:{{primaryTextColor}}");
    return BRAND_COLOURED_LINK.matcher(labelled).replaceAll("color:{{primaryLinkColor}}");
  }

  /** The subject line, from the generated catalogue rather than from the document. */
  public String subjectOf(String templateId, Tone tone) {
    return catalogueCopy(templateId, tone, "subject");
  }

  /** Trusted mailbox preview copy from the same generated catalogue as the subject. */
  public String preheaderOf(String templateId, Tone tone) {
    return catalogueCopy(templateId, tone, "preheader");
  }

  /** Trusted installed preheader for an operator preview, independent of delivery gating. */
  public String preheaderForPreview(String templateId, Tone tone) {
    return catalogueCopyExact(templateId, installedPreviewTone(tone), "preheader");
  }

  private String catalogueCopy(String templateId, Tone tone, String field) {
    return catalogueCopyExact(templateId, deliveryTone(tone), field);
  }

  private String catalogueCopyExact(String templateId, Tone tone, String field) {
    JsonNode node =
        catalogue.path("mails").path(templateId).path("tones").path(tone.directory()).path(field);
    if (node.isMissingNode() || !isNotBlank(node.asText())) {
      throw new IllegalStateException(
          "no " + field + " for e-mail template '" + templateId + "' in tone " + tone.directory());
    }
    return node.asText();
  }

  private Tone installedPreviewTone(Tone tone) {
    if (tone == null) {
      throw new IllegalArgumentException("Preview e-mail locale is missing");
    }
    String release = catalogue.path("locales").path(tone.directory()).path("release").asText();
    if (!"released".equals(release) && !"pending-human-review".equals(release)) {
      throw new IllegalStateException(
          "Unknown e-mail locale release state for " + tone.directory() + ": " + release);
    }
    return tone;
  }

  public Tone deliveryTone(Tone tone) {
    String release = catalogue.path("locales").path(tone.directory()).path("release").asText();
    if ("released".equals(release)
        || ("pending-human-review".equals(release) && allowUnreviewedLocales)) {
      return tone;
    }
    if ("pending-human-review".equals(release)) {
      log.warn(
          "E-mail locale {} awaits human review; using reviewed German copy", tone.directory());
      return Tone.DE_FORMAL;
    }
    throw new IllegalStateException(
        "Unknown e-mail locale release state for " + tone.directory() + ": " + release);
  }

  /** Whether the footer of this occasion offers an unsubscribe link (ADR-019). */
  public boolean isUnsubscribable(String templateId) {
    return catalogue.path("mails").path(templateId).path("unsubscribable").asBoolean(true);
  }

  private String read(String templateId, Tone tone, String extension) {
    String path = BASE + "/" + tone.directory() + "/" + templateId + "." + extension;
    return templateCache.computeIfAbsent(path, this::readResource);
  }

  private String readResource(String path) {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(path)) {
      if (in == null) {
        throw new IllegalStateException(
            "e-mail template " + path + " is missing — run scripts/sync-email-templates.sh");
      }
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read e-mail template " + path, exception);
    }
  }

  private JsonNode loadCatalogue() {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(BASE + "/catalogue.json")) {
      if (in == null) {
        throw new IllegalStateException(
            "emails/catalogue.json is missing — run scripts/sync-email-templates.sh");
      }
      return new ObjectMapper().readTree(in);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read emails/catalogue.json", exception);
    }
  }

  /**
   * Expands the conditional tokens — {@code {{logoCell}}}, {@code {{ctaBlock}}} and {@code
   * {{assuranceBlock}}} — to their markup, or to nothing when the value they depend on is absent.
   * Runs before {@link #substitute}, so the placeholders inside the expanded markup are filled —
   * and escaped — like any other.
   */
  private String withConditionalBlocks(String template, Map<String, String> values, boolean html) {
    boolean hasAction = isNotBlank(values.get("actionUrl"));
    return template
        .replace("{{logoCell}}", isNotBlank(values.get("logoUrl")) ? LOGO_CELL : "")
        .replace("{{ctaBlock}}", hasAction ? (html ? CTA_BLOCK_HTML : CTA_BLOCK_TEXT) : "")
        .replace(
            "{{assuranceBlock}}",
            hasAction ? (html ? ASSURANCE_BLOCK_HTML : ASSURANCE_BLOCK_TEXT) : "");
  }

  private static String withoutBlankContactRows(
      String templateId, String template, Map<String, String> values, boolean html) {
    if (!"beraterin-kontakt".equals(templateId)) {
      return template;
    }
    Matcher matcher = (html ? CONTACT_ROW_HTML : CONTACT_ROW_TEXT).matcher(template);
    StringBuilder result = new StringBuilder();
    boolean dropped = false;
    while (matcher.find()) {
      String value = values.get(matcher.group(1));
      boolean omit = value != null && value.isBlank();
      matcher.appendReplacement(result, omit ? "" : Matcher.quoteReplacement(matcher.group()));
      dropped |= omit;
    }
    matcher.appendTail(result);
    return dropped && !html ? result.toString().replaceAll("\\n{3,}", "\n\n") : result.toString();
  }

  /**
   * Drops every footer line that names a sender value nobody entered (Frank, 2026-09-23): no
   * address means no address line, no organisation means neither its name nor "… ist ein Angebot
   * von …" — never an empty line and never a sample. A {@code div} goes entirely; a {@code td}
   * keeps its cell, because the table around it needs it, and loses its sentence. A value that is
   * missing from {@code values} altogether is left alone, so the placeholder stays visible as a bug
   * report.
   */
  private static String withoutBlankSenderLines(
      String template, Map<String, String> values, boolean html) {
    Matcher matcher = (html ? SENDER_ELEMENT : SENDER_LINE).matcher(template);
    StringBuilder out = new StringBuilder();
    boolean dropped = false;
    while (matcher.find()) {
      if (!namesABlankSenderValue(matcher.group(), values)) {
        matcher.appendReplacement(out, Matcher.quoteReplacement(matcher.group()));
        continue;
      }
      dropped = true;
      String replacement =
          html && "td".equals(matcher.group(1))
              ? "<td" + (matcher.group(2) == null ? "" : matcher.group(2)) + "></td>"
              : "";
      matcher.appendReplacement(out, Matcher.quoteReplacement(replacement));
    }
    matcher.appendTail(out);
    String result = out.toString();
    return dropped && !html ? result.replaceAll("\n{3,}", "\n\n") : result;
  }

  private static boolean namesABlankSenderValue(String line, Map<String, String> values) {
    Matcher placeholder = SENDER_PLACEHOLDER.matcher(line);
    while (placeholder.find()) {
      String value = values.get(placeholder.group(1));
      if (value != null && value.isBlank()) {
        return true;
      }
    }
    return false;
  }

  /** Inserts already-finished fragments verbatim; see {@link #render(String, Tone, Map, Map)}. */
  private static String insertFragments(String document, Map<String, String> fragments) {
    String result = document;
    for (Map.Entry<String, String> fragment : fragments.entrySet()) {
      result =
          result.replace(
              "{{" + fragment.getKey() + "}}",
              fragment.getValue() == null ? "" : fragment.getValue());
    }
    return result;
  }

  /**
   * Substitutes {@code {{placeholders}}}.
   *
   * <p>The HTML part escapes markup-significant characters — a counsellor display name or a tenant
   * name is user-controlled input, and it is being written into a document, not into a log line.
   * The text part does not escape, because there is no markup to protect.
   */
  private String substitute(String source, Map<String, String> values, boolean escape) {
    Matcher matcher = PLACEHOLDER.matcher(source);
    StringBuilder out = new StringBuilder();
    int tail = 0;
    while (matcher.find()) {
      out.append(source, tail, matcher.start());
      tail = matcher.end();
      String replacement = values.get(matcher.group(1));
      if (replacement == null) {
        out.append(matcher.group());
        continue;
      }
      out.append(escape ? escapeHtml(replacement) : replacement);
      // A value ending in an abbreviation ("… e.V.") at the end of a sentence: its dot is the
      // full stop too, so the template's own one would print "e.V..".
      if (replacement.endsWith(".") && source.startsWith(".", tail)) {
        tail++;
      }
    }
    out.append(source, tail, source.length());
    return out.toString();
  }

  private static String escapeHtml(String value) {
    return HtmlUtils.htmlEscape(value, StandardCharsets.UTF_8.name());
  }
}
