package de.caritas.cob.userservice.api.service.email;

import static org.apache.commons.lang3.StringUtils.isNotBlank;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.neovisionaries.i18n.LanguageCode;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.web.util.HtmlUtils;

/**
 * Renders a transactional e-mail from the ORISO e-mail design system.
 *
 * <p>The templates under {@code src/main/resources/emails} are generated by the design system in
 * ORISO-Frontend and copied here by {@code scripts/sync-email-templates.sh} — they are never edited
 * in this repository. Storybook renders the same content model, so what a reviewer approves there
 * is what this class sends. See ADR-020 in ORISO-Frontend.
 *
 * <p>One exception, and it is temporary: {@code einladung-freitext} — the frame around an
 * operator-authored invite text — was added here first, because the invite mail had to leave its
 * hand-written layout before the design system had a generic message template. The sync script
 * refuses to complete while that template is missing from the generated set, so the day it is added
 * in ORISO-Frontend this repository stops being its home without anyone noticing a gap.
 *
 * <p>This service consumes the {@code plain} dialect, which is deliberately not a template engine:
 * the substitution below is the whole of it. Anything cleverer would be a second renderer, and a
 * second renderer is how a mail starts disagreeing with its own design.
 */
@Slf4j
@Component
public class OrisoEmailRenderer {

  private static final String BASE = "/emails";

  private static final Pattern PLACEHOLDER = Pattern.compile("\\{\\{\\s*([\\w.]+)\\s*}}");

  /**
   * The header's logo cell. The templates carry a single {@code {{logoCell}}} token where the
   * design system places the logo, and this is the markup that token expands to when a logo URL is
   * configured. When {@code logoUrl} is blank the token expands to nothing at all: an {@code <img
   * src="">} renders as a broken-image icon next to the platform name, so the text wordmark has to
   * carry the header alone. The platform name always stands in the next cell, so the logo is
   * decorative ({@code alt=""}): a logo that fails to load must not repeat the name beside itself.
   * The dialect has no conditional syntax — this constant is one of the conditionals the mails
   * need, and it stays in the renderer so the markup remains e-mail-client table markup reviewed
   * together with the templates.
   */
  private static final String LOGO_CELL =
      "<td width=\"36\" valign=\"middle\" style=\"width:36px;padding-right:12px;\">"
          + "<img src=\"{{logoUrl}}\" width=\"36\" height=\"36\" alt=\"\""
          + " style=\"display:block;width:36px;height:36px;border:0;border-radius:8px;\"></td>";

  /**
   * The call-to-action button plus the visible copy-paste fallback line, for templates whose action
   * is supplied by the caller rather than fixed in the document (today: {@code
   * einladung-freitext}). The second conditional: a mail whose action URL is absent must not ship a
   * button pointing nowhere, and the dialect cannot express that. Templates with a fixed action —
   * {@code einladung-traeger}, {@code anmeldelink} — carry their own button markup and never see
   * this token.
   */
  private static final String CTA_BLOCK_HTML =
      "<tr><td class=\"sp btn\" align=\"left\" style=\"padding:20px 40px 0px 40px;\">"
          + "<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr>"
          + "<td align=\"center\" bgcolor=\"{{primaryColor}}\""
          + " style=\"background-color:{{primaryColor}};border-radius:999px;\">"
          + "<a href=\"{{actionUrl}}\" style=\"display:inline-block;padding:14px 32px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:16px;"
          + "line-height:20px;font-weight:600;color:#ffffff;text-decoration:none;"
          + "border-radius:999px;\">{{actionLabel}}</a></td></tr></table></td></tr>"
          + "<tr><td class=\"sp\" style=\"padding:16px 40px 0px 40px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;"
          + "line-height:20px;color:#5c5555;word-break:break-word;\">{{fallbackHint}}<br>"
          + "<a href=\"{{actionUrl}}\" style=\"color:{{linkColor}};text-decoration:underline;"
          + "word-break:break-all;\">{{actionUrl}}</a></td></tr>";

  /** The plain-text half of {@link #CTA_BLOCK_HTML}. */
  private static final String CTA_BLOCK_TEXT = "{{actionLabel}}:\n{{actionUrl}}";

  /**
   * The closing fine print inside the card — divider plus the {@code {{assurance}}} line — for
   * templates whose action is optional ({@code einladung-freitext}). It rides on the same condition
   * as {@link #CTA_BLOCK_HTML}: the line tells the recipient to keep the link to themselves, and a
   * mail without an action has no link to keep. The markup is the design system's {@code
   * emailAssurance} molecule, byte for byte.
   */
  private static final String ASSURANCE_BLOCK_HTML =
      "<tr><td class=\"sp\" style=\"padding:28px 40px 0px 40px;\">"
          + "<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\""
          + " border=\"0\"><tr><td height=\"1\" bgcolor=\"#e0dada\""
          + " style=\"height:1px;line-height:1px;font-size:0;\">&nbsp;</td></tr></table></td></tr>"
          + "<tr><td class=\"sp\" style=\"padding:16px 40px 32px 40px;"
          + "font-family:Inter, 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;"
          + "line-height:18px;color:#5c5555;\">{{assurance}}</td></tr>";

  /** The plain-text half of {@link #ASSURANCE_BLOCK_HTML}, divider included like the HTML. */
  private static final String ASSURANCE_BLOCK_TEXT = "-".repeat(64) + "\n{{assurance}}";

  private final Map<String, String> templateCache = new ConcurrentHashMap<>();

  private final JsonNode catalogue;

  public OrisoEmailRenderer() {
    this.catalogue = loadCatalogue();
  }

  /** Both MIME parts plus the subject, ready to hand to a {@code MimeMessage}. */
  public record RenderedEmail(String subject, String html, String text) {}

  /**
   * Tone variant. German ships twice because the address form is a per-tenant decision; this
   * service has no tenant tone setting yet, so German resolves to the formal variant.
   */
  public enum Tone {
    DE_FORMAL("de-sie"),
    DE_INFORMAL("de-du"),
    EN("en");

    private final String directory;

    Tone(String directory) {
      this.directory = directory;
    }

    public String directory() {
      return directory;
    }

    public static Tone of(LanguageCode languageCode) {
      return languageCode != null && "en".equalsIgnoreCase(languageCode.name()) ? EN : DE_FORMAL;
    }
  }

  /**
   * Renders one mail.
   *
   * @param templateId an id from {@code catalogue.json}, e.g. {@code anmeldelink}
   * @param values one entry per {@code {{placeholder}}} the template needs; a missing key leaves
   *     the placeholder visible rather than blanking it, because a visible {@code {{foo}}} is a bug
   *     report and a silent blank is not
   */
  public RenderedEmail render(String templateId, Tone tone, Map<String, String> values) {
    return render(templateId, tone, values, Map.of());
  }

  /**
   * Renders one mail, with some slots filled by markup the caller has already produced.
   *
   * <p>{@code fragments} exists for exactly one thing the escaping substitution cannot do: a body
   * that is authored elsewhere and arrives as a finished, already-sanitised HTML fragment (see
   * {@code einladung-freitext}, whose body an operator writes in the Admin panel). Those values are
   * inserted <em>after</em> substitution and are never re-scanned, so a fragment can neither be
   * escaped into visible tag soup nor smuggle a {@code {{placeholder}}} of its own into the
   * document. Everything a template can express without that — every ordinary value — belongs in
   * {@code values}, where it is escaped.
   *
   * @param fragments placeholder name → verbatim replacement; the caller is responsible for the
   *     safety of what it puts in here
   */
  public RenderedEmail render(
      String templateId, Tone tone, Map<String, String> values, Map<String, String> fragments) {
    values = withOccasionOnUnsubscribeLink(templateId, values);
    String html =
        substitute(
            withConditionalBlocks(read(templateId, tone, "html"), values, true), values, true);
    String text =
        substitute(
            withConditionalBlocks(read(templateId, tone, "txt"), values, false), values, false);
    String subject = substitute(subjectOf(templateId, tone), values, false);
    return new RenderedEmail(
        insertFragments(subject, fragments),
        insertFragments(html, fragments),
        insertFragments(text, fragments));
  }

  /**
   * Tells the unsubscribe link which mail it came from.
   *
   * <p>A footer link that lands on a settings screen full of switches leaves the recipient to work
   * out which one produced the mail in their hand. Carrying the occasion lets the screen focus the
   * right switch — see ORISO-Frontend#872, which is the other half of this.
   *
   * <p>A security or legal mail has no unsubscribe link at all, so there is nothing to decorate.
   */
  private Map<String, String> withOccasionOnUnsubscribeLink(
      String templateId, Map<String, String> values) {
    String link = values.get("unsubscribeUrl");
    if (!isUnsubscribable(templateId) || link == null || link.isBlank()) {
      return values;
    }
    Map<String, String> decorated = new LinkedHashMap<>(values);
    decorated.put("unsubscribeUrl", link + (link.contains("?") ? "&" : "?") + "mail=" + templateId);
    return decorated;
  }

  /** The subject line, from the generated catalogue rather than from the document. */
  public String subjectOf(String templateId, Tone tone) {
    JsonNode node =
        catalogue
            .path("mails")
            .path(templateId)
            .path("tones")
            .path(tone.directory())
            .path("subject");
    if (node.isMissingNode() || !isNotBlank(node.asText())) {
      throw new IllegalStateException(
          "no subject for e-mail template '" + templateId + "' in tone " + tone.directory());
    }
    return node.asText();
  }

  /** Whether the footer of this occasion offers an unsubscribe link (ADR-019). */
  public boolean isUnsubscribable(String templateId) {
    return catalogue.path("mails").path(templateId).path("unsubscribable").asBoolean(true);
  }

  private String read(String templateId, Tone tone, String extension) {
    String path = BASE + "/" + tone.directory() + "/" + templateId + "." + extension;
    return templateCache.computeIfAbsent(path, this::readResource);
  }

  private String readResource(String path) {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(path)) {
      if (in == null) {
        throw new IllegalStateException(
            "e-mail template " + path + " is missing — run scripts/sync-email-templates.sh");
      }
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read e-mail template " + path, exception);
    }
  }

  private JsonNode loadCatalogue() {
    try (InputStream in = OrisoEmailRenderer.class.getResourceAsStream(BASE + "/catalogue.json")) {
      if (in == null) {
        throw new IllegalStateException(
            "emails/catalogue.json is missing — run scripts/sync-email-templates.sh");
      }
      return new ObjectMapper().readTree(in);
    } catch (IOException exception) {
      throw new IllegalStateException("could not read emails/catalogue.json", exception);
    }
  }

  /**
   * Expands the conditional tokens — {@code {{logoCell}}}, {@code {{ctaBlock}}} and {@code
   * {{assuranceBlock}}} — to their markup, or to nothing when the value they depend on is absent.
   * Runs before {@link #substitute}, so the placeholders inside the expanded markup are filled —
   * and escaped — like any other.
   */
  private String withConditionalBlocks(String template, Map<String, String> values, boolean html) {
    boolean hasAction = isNotBlank(values.get("actionUrl"));
    return template
        .replace("{{logoCell}}", isNotBlank(values.get("logoUrl")) ? LOGO_CELL : "")
        .replace("{{ctaBlock}}", hasAction ? (html ? CTA_BLOCK_HTML : CTA_BLOCK_TEXT) : "")
        .replace(
            "{{assuranceBlock}}",
            hasAction ? (html ? ASSURANCE_BLOCK_HTML : ASSURANCE_BLOCK_TEXT) : "");
  }

  /** Inserts already-finished fragments verbatim; see {@link #render(String, Tone, Map, Map)}. */
  private static String insertFragments(String document, Map<String, String> fragments) {
    String result = document;
    for (Map.Entry<String, String> fragment : fragments.entrySet()) {
      result =
          result.replace(
              "{{" + fragment.getKey() + "}}",
              fragment.getValue() == null ? "" : fragment.getValue());
    }
    return result;
  }

  /**
   * Substitutes {@code {{placeholders}}}.
   *
   * <p>The HTML part escapes markup-significant characters — a counsellor display name or a tenant
   * name is user-controlled input, and it is being written into a document, not into a log line.
   * The text part does not escape, because there is no markup to protect.
   */
  private String substitute(String source, Map<String, String> values, boolean escape) {
    Matcher matcher = PLACEHOLDER.matcher(source);
    StringBuilder out = new StringBuilder();
    while (matcher.find()) {
      String replacement = values.get(matcher.group(1));
      if (replacement == null) {
        matcher.appendReplacement(out, Matcher.quoteReplacement(matcher.group()));
        continue;
      }
      matcher.appendReplacement(
          out, Matcher.quoteReplacement(escape ? escapeHtml(replacement) : replacement));
    }
    matcher.appendTail(out);
    return out.toString();
  }

  private static String escapeHtml(String value) {
    return HtmlUtils.htmlEscape(value, StandardCharsets.UTF_8.name());
  }
}
